# config/packages/messenger.yaml
framework:
  messenger:
    failure_transport: failed
    transports:
      async_high:
        dsn: '%env(AMQP_DSN)%'
        options:
          exchange: { name: emails_high, type: direct }
          queues:
            emails_high: ~
        retry_strategy: { max_retries: 5, delay: 1000, multiplier: 2.0, max_delay: 60000 }

      async:
        dsn: '%env(AMQP_DSN)%'
        options:
          exchange: { name: emails, type: direct }
          queues:
            emails: ~
        retry_strategy: { max_retries: 5, delay: 1000, multiplier: 2.0, max_delay: 60000 }

      async_low:
        dsn: '%env(AMQP_DSN)%'
        options:
          exchange: { name: emails_low, type: direct }
          queues:
            emails_low: ~
        retry_strategy: { max_retries: 5, delay: 1000, multiplier: 2.0, max_delay: 60000 }

      failed: 'doctrine://default?queue_name=failed&auto_setup=1'

    routing:
      App\Message\SendEmailMessage: async
