services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - rabbitmq
      - mailhog

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - rabbitmq
      - db
    command: >
      bash -lc "php bin/console messenger:consume async_high async async_low -vv"

volumes:
  db-data:
